services:
  app-prod:
    container_name: mttp
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:prod"]
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: prod