version: '3.8'

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:dev"]
    ports:
      - "3001:3000"
    environment:
      NODE_ENV: dev

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:prod"]
    ports:
      - "3002:3000"
    environment:
      NODE_ENV: prod