services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:dev"]
    environment:
      NODE_ENV: dev

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["npm", "run", "start:prod"]
    environment:
      NODE_ENV: prod